"""Add KYC tables

Revision ID: 64b46d58cc98
Revises: eb6bbfc4bb72
Create Date: 2026-05-27 16:24:03.962190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64b46d58cc98'
down_revision: Union[str, None] = 'eb6bbfc4bb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_submission_id'), 'kyc_documents', ['submission_id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_user_id'), 'kyc_documents', ['user_id'], unique=False)
    op.create_table('kyc_status_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_status_logs_submission_id'), 'kyc_status_logs', ['submission_id'], unique=False)
    op.create_index(op.f('ix_kyc_status_logs_user_id'), 'kyc_status_logs', ['user_id'], unique=False)
    op.create_table('kyc_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_legal_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('country_of_residence', sa.String(), nullable=False),
    sa.Column('residential_address', sa.String(), nullable=False),
    sa.Column('source_of_funds', sa.String(), nullable=False),
    sa.Column('source_of_funds_details', sa.String(), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_submissions_user_id'), 'kyc_submissions', ['user_id'], unique=False)
    op.drop_index('ix_investor_security_user_id', table_name='investor_security')
    op.drop_table('investor_security')
    op.drop_index('ix_recovery_logs_user_id', table_name='recovery_logs')
    op.drop_table('recovery_logs')
    op.drop_index('ix_recovery_requests_user_id', table_name='recovery_requests')
    op.drop_table('recovery_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_requests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kyc_document_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_liveness_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recovery_requests_pkey')
    )
    op.create_index('ix_recovery_requests_user_id', 'recovery_requests', ['user_id'], unique=False)
    op.create_table('recovery_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recovery_logs_pkey')
    )
    op.create_index('ix_recovery_logs_user_id', 'recovery_logs', ['user_id'], unique=False)
    op.create_table('investor_security',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('two_fa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('two_fa_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('totp_secret_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recovery_codes_hash', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recovery_codes_remaining', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recovery_codes_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('re_enrollment_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('two_fa_enabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='investor_security_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='investor_security_pkey')
    )
    op.create_index('ix_investor_security_user_id', 'investor_security', ['user_id'], unique=True)
    op.drop_index(op.f('ix_kyc_submissions_user_id'), table_name='kyc_submissions')
    op.drop_table('kyc_submissions')
    op.drop_index(op.f('ix_kyc_status_logs_user_id'), table_name='kyc_status_logs')
    op.drop_index(op.f('ix_kyc_status_logs_submission_id'), table_name='kyc_status_logs')
    op.drop_table('kyc_status_logs')
    op.drop_index(op.f('ix_kyc_documents_user_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_submission_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    # ### end Alembic commands ###
