"""Add 2FA tables

Revision ID: 8929063e9917
Revises: 87b0779ee677
Create Date: 2026-05-26 16:06:54.532875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8929063e9917'
down_revision: Union[str, None] = '87b0779ee677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_logs_user_id'), 'recovery_logs', ['user_id'], unique=False)
    op.create_table('recovery_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('kyc_document_url', sa.String(), nullable=True),
    sa.Column('video_liveness_url', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_requests_user_id'), 'recovery_requests', ['user_id'], unique=False)
    op.create_table('investor_security',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_fa_status', sa.String(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(), nullable=True),
    sa.Column('recovery_codes_hash', sa.JSON(), nullable=True),
    sa.Column('recovery_codes_remaining', sa.String(), nullable=False),
    sa.Column('recovery_codes_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('re_enrollment_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('two_fa_enabled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_security_user_id'), 'investor_security', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investor_security_user_id'), table_name='investor_security')
    op.drop_table('investor_security')
    op.drop_index(op.f('ix_recovery_requests_user_id'), table_name='recovery_requests')
    op.drop_table('recovery_requests')
    op.drop_index(op.f('ix_recovery_logs_user_id'), table_name='recovery_logs')
    op.drop_table('recovery_logs')
    # ### end Alembic commands ###
