"""Add suitability questionnaire tables

Revision ID: aec47ab74cb0
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 21:40:19.092188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec47ab74cb0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_suitability',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kyc_profile_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.SmallInteger(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('warning_reasons', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('submission_ip', postgresql.INET(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retake_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['investor_suitability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_suitability_completed_at'), 'investor_suitability', ['completed_at'], unique=False)
    op.create_index(op.f('ix_investor_suitability_expires_at'), 'investor_suitability', ['expires_at'], unique=False)
    op.create_index(op.f('ix_investor_suitability_tenant_id'), 'investor_suitability', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_investor_suitability_user_id'), 'investor_suitability', ['user_id'], unique=False)
    op.create_table('suitability_acknowledgements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('suitability_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('property_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suitability_id'], ['investor_suitability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suitability_acknowledgements_suitability_id'), 'suitability_acknowledgements', ['suitability_id'], unique=False)
    op.create_table('suitability_retake_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('previous_suitability_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_suitability_id'], ['investor_suitability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suitability_retake_requests')
    op.drop_index(op.f('ix_suitability_acknowledgements_suitability_id'), table_name='suitability_acknowledgements')
    op.drop_table('suitability_acknowledgements')
    op.drop_index(op.f('ix_investor_suitability_user_id'), table_name='investor_suitability')
    op.drop_index(op.f('ix_investor_suitability_tenant_id'), table_name='investor_suitability')
    op.drop_index(op.f('ix_investor_suitability_expires_at'), table_name='investor_suitability')
    op.drop_index(op.f('ix_investor_suitability_completed_at'), table_name='investor_suitability')
    op.drop_table('investor_suitability')
    # ### end Alembic commands ###
