"""Add investors table

Revision ID: eb6bbfc4bb72
Revises: 8929063e9917
Create Date: 2026-05-27 15:39:33.536381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6bbfc4bb72'
down_revision: Union[str, None] = '8929063e9917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_fa_status', sa.String(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(), nullable=True),
    sa.Column('recovery_codes_hash', sa.String(), nullable=True),
    sa.Column('recovery_codes_remaining', sa.String(), nullable=False),
    sa.Column('recovery_codes_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('re_enrollment_deadline', sa.DateTime(), nullable=True),
    sa.Column('two_fa_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investors_user_id'), 'investors', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investors_user_id'), table_name='investors')
    op.drop_table('investors')
    # ### end Alembic commands ###
